name: "Choreo Source Configuration Validator"
description: "Validate the source configuration files of Choreo"
inputs:
  source-root-dir: # the path to root directory of the source code
    description: "path to the root directory of the source code"
    required: true
    default: ""
outputs:
  validation-result: # result of the validation
    description: "The result of the validation"
runs:
  using: "node20"
  main: "dist/index.js"
